language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - py.test # or py.test for Python versions 3.5 and below